name: expense_tracker
description: A simple expense tracker app using Firebase.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

environment:
  sdk: "^3.7.0"  # เพิ่มบรรทัดนี้

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.7.0
  provider: ^6.0.4
  flutter_application_1: ^0.0.2
  image_picker: ^1.1.2
  firebase_storage: ^11.7.7
  intl: ^0.17.0
  flutter_svg: ^2.0.10
  shared_preferences: ^2.0.15 # Ensure this line is present
  country_picker: ^2.0.17 # Add this line

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true # Change to true
  ios: true
  image_path: "assets/icons/wallet.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/receipt.png
    - assets/icons/money.png
    - assets/icons/updown.png
    - assets/icons/logout.png
    - assets/icons/user.png
    - assets/icons/backward.png