// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvS1U4vxuPhmwp7wn0rtDt8qk1vCqq1LQ',
    appId: '1:402979896367:web:4b94b194e7ab6cc0935ada',
    messagingSenderId: '402979896367',
    projectId: 'project-final-21333',
    authDomain: 'project-final-21333.firebaseapp.com',
    storageBucket: 'project-final-21333.firebasestorage.app',
    measurementId: 'G-0LLTNKPQ0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEi9AAYkUmiZxuwJzvEWnIXcdEcjYI-HY',
    appId: '1:402979896367:android:bee4220bb4a40197935ada',
    messagingSenderId: '402979896367',
    projectId: 'project-final-21333',
    storageBucket: 'project-final-21333.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7ryyETT60z94P3m4cxR2Him7oRMvSyeo',
    appId: '1:402979896367:ios:1d52f5c09cd18425935ada',
    messagingSenderId: '402979896367',
    projectId: 'project-final-21333',
    storageBucket: 'project-final-21333.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7ryyETT60z94P3m4cxR2Him7oRMvSyeo',
    appId: '1:402979896367:ios:1d52f5c09cd18425935ada',
    messagingSenderId: '402979896367',
    projectId: 'project-final-21333',
    storageBucket: 'project-final-21333.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvS1U4vxuPhmwp7wn0rtDt8qk1vCqq1LQ',
    appId: '1:402979896367:web:73817c41d180eae9935ada',
    messagingSenderId: '402979896367',
    projectId: 'project-final-21333',
    authDomain: 'project-final-21333.firebaseapp.com',
    storageBucket: 'project-final-21333.firebasestorage.app',
    measurementId: 'G-BK4E7DENBK',
  );
}
